### PR TITLE
added ppx_withStyles for linux

### LINKED ISSUE #7: ppx_WithStyle doesn't work for linux
Current ppx works with Mac, but it has problem to run on linux. Do you have a version for linux??

### PR DESCRIPTION
**Pull request by liamcurry**
This PR adds a version of `ppx_withStyles` that was compiled and working on Linux and should fix #7.

Since there are 2 versions of this file now, I've added a suffix for different operating systems, so there is a new file `ppx_withStyles_linux` and the old `ppx_withStyles` file has become `ppx_withStyles_mac`. Not a big deal IMO but it could be considered a breaking change I guess.

I don't know much about cross compiling OCaml so if other Linux users could test this out it would be greatly appreciated. Thanks.

### CODE REVIEW

**Comment by studious** [comment]
This works nicely. What I would really appreciate is a postInstall script like the graphql_ppx library has that grabs the correct arch binary and copies it to a consistent named location. Then the bsconfig can remain the same but be installed on either my host (mac) or docker (linux).

**Comment by jsiebern** [comment]
@liamcurry I just pushed to master, could you place your binary under `bin/ppx_withStyles-linux-x64` please? I'll merge the request once that is done and will publish a beta for testing after!

**Comment by liamcurry** [comment]
@jsiebern I moved the binary to that location and updated the README

**Comment by liamcurry** [comment]
@jsiebern here is the `post-install` script that @studious mentioned: https://github.com/mhallin/graphql_ppx/blob/master/copyPlatformBinaryInPlace.js

**Comment by jsiebern** [comment]
@liamcurry Thanks, I implemented it already in my last push :)

**Comment by liamcurry** [comment]
@jsiebern Nice one! I just created #15 to revert the README file changes that were included in this PR

**Pull request merged**
