### PR TITLE
Update to @rescript/react 0.10

### LINKED ISSUE #120: Rescript incompatibility
Hi!

I just installed these bindings in a Rescript project, unfortunately I am getting the following error:

```bash
  It's possible that your build is stale.
  Try to clean the artifacts and build again?

  Here's the original error message
  The files /Users/fernando/Code/rescript/node_modules/@jsiebern/bs-material-ui/lib/ocaml/materialUi.cmi
  and /Users/fernando/Code/rescript/node_modules/@rescript/react/lib/ocaml/react.cmi
  make inconsistent assumptions over interface React

FAILED: cannot make progress due to previous errors.
>>>> Finish compiling(exit: 1)
```

My code:
```res
// Main.res
@react.component
let make = () => {
  open MaterialUi
  <Container>
    {React.string("Hello World")}
  </Container> 
}
```

package.json
```json
{
  "scripts": {
    "re:build": "bsb -make-world -clean-world",
    "re:watch": "bsb -make-world -clean-world -w"
  },
  "dependencies": {
    "@jsiebern/bs-material-ui": "2.0.2",
    "@material-ui/core": "4.11.3",
    "@rescript/react": "0.10.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "reason-react": "^0.9.1",
    "snowpack": "3.0.11"
  }
}
```

bsconfig.json
```json
{
  "name": "rescript",
  "reason": { "react-jsx": 3 },
  "bs-dependencies": ["@rescript/react", "@jsiebern/bs-material-ui"],
  "bsc-flags": ["-bs-super-errors"],
  "sources": [
    {
      "dir": "src",
      "subdirs": true
    }
  ],
  "package-specs": [
    {
      "module": "es6",
      "in-source": true
    }
  ],
  "suffix": ".bs.js",
  "namespace": true,
  "ppx-flags": [],
  "refmt": 3
}

```

It is there anything I can do to make it work? Thanks!

### PR DESCRIPTION
**Pull request by dodomorandi**
This is hopefully helpful to migrate from `reason-react` to `@rescript/react`. This is obviously a breaking change.
I am not totally sure everything is fine, because I encountered some issues during the building process and I locally made some changes (not committed, obviously) to being able to build everything.

The main change to the code generated is `ReactDOMRe` -> `ReactDOM`, which mainly influences reference to `ReactDOMRe.Style.t` and `ReactDOMRe.domRef`. I hope that this change is fine, in case let me know.

Give a look to the second commit as well: it is just a fix to a test, which had an hardcoded path that could not work. If you want, I can just split it in another PR.

Closes #120.

Thank you anyway for your work. Really appreciated!

### CODE REVIEW

**Comment by dodomorandi** [comment]
There is a missing piece I did not notice: [@mscharley/bs-material-ui-icons](https://github.com/mscharley/bs-material-ui-icons) must be updated to use `@rescript/react/ as well. I will open an issue and see if the author is interested in the migration, otherwise I could try to incorporate the package in this repo. Regarding the last possibility, from one point of view, it's more code to maintain unfortunately, but at the same time it would make this project free from external deps.

**Comment by dodomorandi** [comment]
I did not receive response from the author of the repo dedicated to MUI icons, and in the end I wrote the support for `bs-material-ui`. I am not sure this is the best solution -- it adds lots of modules to the project, but on the other hand they needed to be build anyway.

Let me know what you think, I am open to other solutions.

**Comment by dodomorandi** [comment]
I just received a reply from the author of `bs-material-ui-icons`, as soon as we have a new version I will revert https://github.com/jsiebern/bs-material-ui/pull/121/commits/383e21ba274cc85690e46923c4f231148b899cca and rely on the external package. This specific commit introduces too much overhead, and I strongly believe that handling the feature separately is the best way.

**Comment by dodomorandi** [comment]
Things looks better now. Let me know what you think, if you want me to make changes and if you want me to squash commits together. Thank you!

**Comment by jsiebern** [comment]
Hey, thanks for your work, I'll look it over today and try to update! Crazy situation at work the past weeks, so sorry I couldn't get to it sooner.

**Comment by Phylodome** [comment]
Any updates on the timeline?

Presently planning a project's transition to ReScript and would benefit from some forward guidance.

**Comment by jsiebern** [comment]
@dodomorandi Thanks again for this PR - you really put some thought into understanding the mess this generator is. I profoundly apologize for not checking out your commits in detail earlier. Everything is done, as they are complete and target the generator (understandably, most PRs before just target the generated files). Thank you.

@Phylodome Hopefully within the hour :)

**Comment by Ferdzzzzzzzz** [comment]
@jsiebern what version will this release be? :)

**Comment by jsiebern** [comment]
@Ferdzzzzzzzz It will be 2.1.0 in a bit, just need to fix some weird theme error in the examples

**Comment by jsiebern** [comment]
I gotta start work - could someone help me out and try to run the examples on the latest commit? Some hooks error within Mui, but not feeling comfortable updating the package before this is resolved.

**Comment by dodomorandi** [comment]
I am glad to help! I will try to give it a look as soon I have some spare time :blush:

**Pull request merged**
